<?php


namespace Tests\Feature;


use Tests\CustomTestCase;

class ThreadTest extends CustomTestCase
{
    private $threadProperties =[
            "id",
            "created_at",
            "updated_at",
            "body",
            "user_id",
    ];
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_getThreads(){
          create('App\Thread');
          $threadResultStructure = [
              "*"=>$this->threadProperties
          ];
         $result= $this->getJson('/api/threads')
            ->assertStatus(200)
            ->assertJsonStructure(
                $this->getResponsePaginationJsonStructure($threadResultStructure)
            )->json();
         $this->assertCount(1,$result['data']);
    }
}
